Added and Fixed "Copy" Button implementation.
choraria/gas-url-shortener pull request #44
Opened 2020-07-26 18:45 UTC by tulXoro

I was able to make and test a button that copies the link.

I did this by making another div and button which should appear when the link is generated.

It should work by selecting (or "highlighting") the link, and copy it into the user's clipboard. However, it still has no style, and it doesn't notify the user that it has been copied either. Let me know if there's anything I should change or edit.

2020-07-27 10:27 UTC, saxobroko requested changes
Works exactly as intended but could use some styling improvements.

2020-07-27 13:46 UTC, tulXoro commented
Ok, how should I style it?

2020-07-27 23:34 UTC, tulXoro commented
How does that look?

2020-07-28 06:51 UTC, saxobroko approved these changes

2024-02-15 07:37 UTC, closed without merging